// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: spotifyDevice-UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_playScreen
void ui_playScreen_screen_init(void);
lv_obj_t *ui_playScreen;
lv_obj_t *ui_mainControlContainer;
void ui_event_mainPlayBtn( lv_event_t * e);
lv_obj_t *ui_mainPlayBtn;
void ui_event_mainPauseBtn( lv_event_t * e);
lv_obj_t *ui_mainPauseBtn;
void ui_event_mainPrevBtn( lv_event_t * e);
lv_obj_t *ui_mainPrevBtn;
void ui_event_mainNextBtn( lv_event_t * e);
lv_obj_t *ui_mainNextBtn;
void ui_event_mainShuffleBtn( lv_event_t * e);
lv_obj_t *ui_mainShuffleBtn;
void ui_event_mainRepeatBtn( lv_event_t * e);
lv_obj_t *ui_mainRepeatBtn;
lv_obj_t *ui_mainProgressBar;
lv_obj_t *ui_mainProgressLbl;
lv_obj_t *ui_mainSongLenLbl;
lv_obj_t *ui_mainDisplayContainer;
lv_obj_t *ui_mainCoverImg;
lv_obj_t *ui_mainSongLbl;
lv_obj_t *ui_mainArtistLbl;
lv_obj_t *ui_mainContextLbl;
lv_obj_t *ui_mainNowPlayingStr;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_mainPlayBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_mainPlayBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
      _ui_flag_modify( ui_mainPauseBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
      playSong( e );
}
}
void ui_event_mainPauseBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_mainPlayBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
      _ui_flag_modify( ui_mainPauseBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
      pauseSong( e );
}
}
void ui_event_mainPrevBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      prevSong( e );
}
}
void ui_event_mainNextBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      nextSong( e );
}
}
void ui_event_mainShuffleBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      toggleShuffle( e );
}
}
void ui_event_mainRepeatBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      toggleRepeat( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_playScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_playScreen);
}
