// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: spotifyDevice-UI

#ifndef _SPOTIFYDEVICE_UI_UI_H
#define _SPOTIFYDEVICE_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_playScreen
void ui_playScreen_screen_init(void);
extern lv_obj_t *ui_playScreen;
extern lv_obj_t *ui_mainControlContainer;
void ui_event_mainPlayBtn( lv_event_t * e);
extern lv_obj_t *ui_mainPlayBtn;
void ui_event_mainPauseBtn( lv_event_t * e);
extern lv_obj_t *ui_mainPauseBtn;
void ui_event_mainPrevBtn( lv_event_t * e);
extern lv_obj_t *ui_mainPrevBtn;
void ui_event_mainNextBtn( lv_event_t * e);
extern lv_obj_t *ui_mainNextBtn;
void ui_event_mainShuffleBtn( lv_event_t * e);
extern lv_obj_t *ui_mainShuffleBtn;
void ui_event_mainRepeatBtn( lv_event_t * e);
extern lv_obj_t *ui_mainRepeatBtn;
extern lv_obj_t *ui_mainProgressBar;
extern lv_obj_t *ui_mainProgressLbl;
extern lv_obj_t *ui_mainSongLenLbl;
extern lv_obj_t *ui_mainDisplayContainer;
extern lv_obj_t *ui_mainCoverImg;
extern lv_obj_t *ui_mainSongLbl;
extern lv_obj_t *ui_mainArtistLbl;
extern lv_obj_t *ui_mainContextLbl;
extern lv_obj_t *ui_mainNowPlayingStr;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_playicon_png);   // assets/playIcon.png
LV_IMG_DECLARE( ui_img_pauseicon_png);   // assets/pauseIcon.png
LV_IMG_DECLARE( ui_img_previcon_png);   // assets/prevIcon.png
LV_IMG_DECLARE( ui_img_nexticon_png);   // assets/nextIcon.png
LV_IMG_DECLARE( ui_img_shuffleicon_png);   // assets/shuffleIcon.png
LV_IMG_DECLARE( ui_img_repeaticon_png);   // assets/repeatIcon.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
