// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: spotifyDevice-UI

#include "ui.h"

void playSong(lv_event_t * e)
{
	// Your code here
}

void pauseSong(lv_event_t * e)
{
	// Your code here
}

void prevSong(lv_event_t * e)
{
	// Your code here
}

void nextSong(lv_event_t * e)
{
	// Your code here
}

void toggleShuffle(lv_event_t * e)
{
	// Your code here
}

void toggleRepeat(lv_event_t * e)
{
	// Your code here
}
