// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: spotifyDevice-UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void playSong(lv_event_t * e);
void pauseSong(lv_event_t * e);
void prevSong(lv_event_t * e);
void nextSong(lv_event_t * e);
void toggleShuffle(lv_event_t * e);
void toggleRepeat(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
